### ISSUE TITLE
useAppKitProvider example is missing argument of type 'ChainNamespace'

### ISSUE THREAD

**Issue by gotnoshoeson** [reown-com/reown-docs#102]
### Describe the bug

Where to find the issue: [https://docs.reown.com/appkit/react/core/hooks?platform=ethers#useappkitprovider](https://docs.reown.com/appkit/react/core/hooks?platform=ethers#useappkitprovider )

The example code should have a comment for the options that this argument takes and should show one being implemented.

Current Example:
```
function Components() {
     const { walletProvider } = useAppKitProvider()
      ...
```

Proposed Example:
```
function Components() {
     const { walletProvider } = useAppKitProvider("eip155");
     // Add comments here for all of the possible options of ChainNamespace
```

**Comment by rtomas** [comment]
This PR is awaiting approval.
https://github.com/reown-com/reown-docs/pull/97
